In [318]:
import pandas as pd

# Задание первое
data = pd.read_csv("horse_data.csv", sep=";", na_values=['?'])
horses = pd.DataFrame()
horses['surgery?'] = data.iloc[: , 0]
horses['Age'] = pd.to_numeric(data.iloc[: , 1])
horses['rectal_temperature'] = data.iloc[: , 3]
horses['pulse'] = data.iloc[: , 4]
horses['respiratory_rate'] = data.iloc[: , 5]
horses['temperature_of_extremities'] = data.iloc[: , 6]
horses['pain'] = data.iloc[: , 10]
horses['outcome'] = data.iloc[: , 22]
horses.to_csv('horses.csv', index=False)
horses.head(10)

,surgery?,Age,rectal_temperature,pulse,respiratory_rate,temperature_of_extremities,pain,outcome
0,2.0,1,38.5,66.0,28.0,3.0,5.0,2.0
1,1.0,1,39.2,88.0,20.0,NaN,3.0,3.0
2,2.0,1,38.3,40.0,24.0,1.0,3.0,1.0
3,1.0,9,39.1,164.0,84.0,4.0,2.0,2.0
4,2.0,1,37.3,104.0,35.0,NaN,NaN,2.0
5,2.0,1,NaN,NaN,NaN,2.0,2.0,1.0
6,1.0,1,37.9,48.0,16.0,1.0,3.0,1.0
7,1.0,1,NaN,60.0,NaN,3.0,NaN,2.0
8,2.0,1,NaN,80.0,36.0,3.0,4.0,3.0
9,2.0,9,38.3,90.0,NaN,1.0,5.0,1.0

In [319]:
# Задание второе
print("Средний возраст:", horses.Age.mean())
print("Средний пульс:", horses['pulse'].mean())
print("Средняя ректальная температура:", horses['rectal_temperature'].mean())
print("Средняя частота дыхания:", horses['respiratory_rate'].mean())
print("Медиана частоты дыхания:", horses['respiratory_rate'].median())
print("Выброс частоты дыхания:", horses['respiratory_rate'].mean() - horses['respiratory_rate'].median())

Средний возраст: 1.64
Средний пульс: 71.91304347826087
Средняя ректальная температура: 38.16791666666669
Средняя частота дыхания: 30.417355371900825
Медиана частоты дыхания: 24.5
Выброс частоты дыхания: 5.917355371900825

In [320]:
print(horses.isna().sum())


horses['surgery?'].fillna(horses['surgery?'].median(), inplace=True)

# В зависимости от возраста расчитываю среднюю температуру
horses['rectal_temperature'].fillna(horses.groupby('Age')\
                                    ['rectal_temperature'].transform('mean'), inplace=True)
# В зависимости от возраста расчитываю среднюю частоту дыхания
horses['respiratory_rate'].fillna(horses.groupby(['Age'])\
                                    ['respiratory_rate'].transform('mean'), inplace=True)
# Исходя из возраста и температуры рассчет медианы пульса
horses['pulse'].fillna(horses.groupby(['Age', 'rectal_temperature'])\
                                    ['pulse'].transform('median'), inplace=True)
# По частоте дыхания
horses['pain'].fillna(horses.groupby(['respiratory_rate'])\
                                    ['pain'].transform('median'), inplace=True)
# По температуре тела
horses['temperature_of_extremities'].fillna(horses.groupby(['rectal_temperature'])\
                                    ['temperature_of_extremities'].transform('median'), inplace=True)

# Заполняю оставшиеся пропуски медианами
horses['temperature_of_extremities'].fillna(horses['temperature_of_extremities'].median(), inplace=True)
horses['pain'].fillna(horses['pain'].median(), inplace=True)
horses['outcome'].fillna(horses['outcome'].median(), inplace=True)

horses['rectal_temperature'] = horses['rectal_temperature'].round(1)
horses['respiratory_rate'] = horses['respiratory_rate'].round(1)
horses['pulse'] = horses['pulse'].round(1)
print(horses.isna().sum())

horses.to_csv('output.csv', index=False)

surgery?                       1
Age                            0
rectal_temperature            60
pulse                         24
respiratory_rate              58
temperature_of_extremities    56
pain                          55
outcome                        1
dtype: int64
surgery?                      0
Age                           0
rectal_temperature            0
pulse                         0
respiratory_rate              0
temperature_of_extremities    0
pain                          0
outcome                       0
dtype: int64